name: Run Cypress on pull request to main

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Node.js is installed
        run: node --version -or echo 'Node.js is not installed'
        id: check_node_installed
        continue-on-error: true

      - name: Install Node.js and npm
        if: steps.check_node_installed.outcome == 'failure'
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies in server directory
        run: npm install
        working-directory: server/

      - name: Check if mongod is running
        run: ps aux | grep -v grep | grep mongod -or echo 'mongod is not running'
        id: check_mongod_running
        continue-on-error: true

      - name: Run mongod if not running
        if: steps.check_mongod_running.outcome == 'failure'
        run: net start MongoDB
        continue-on-error: true

      - name: Set DB_URL variable
        run: echo "DB_URL=mongodb://127.0.0.1:27017/fake_so" >> $GITHUB_ENV

      - name: Run remove_db.js
        env:
          DB_URL: ${{ env.DB_URL }}
        run: node remove_db.js mongodb://127.0.0.1:27017/fake_so
        working-directory: server/

      - name: Start the node server
        run: start node server.js
        working-directory: server/

      - name: Install dependencies in client directory
        run: npm install
        working-directory: client/

      - name: Start the Client
        run: start npm start
        working-directory: client/

      - name: Wait for client
        run: npx wait-on http://localhost:3000

      - name: Install testing dependencies
        run: npm install cypress
        working-directory: client/

      - name: Run e2e tests
        run: npx cypress run --e2e
        working-directory: client/

      - name: Run component tests
        run: npx cypress run --component
        working-directory: client/

      - name: Kill the node server process
        run: Stop-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess -Force -ErrorAction SilentlyContinue

      - name: Stop the client process
        run: Stop-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess -Force -ErrorAction SilentlyContinue
