name: Run Cypress on pull request to main

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: nick-host
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies on the server
        run: npm install
        working-directory: server/

      - run: npm run test --runInBand
        working-directory: server/